### ISSUE TITLE
how can i connect the feelworld L1 to this?

### ISSUE THREAD

**Issue by JerryK26** [RedyAu/multitally#1]
I like this app so much, since it really going to solve a huge problem for me.
However, I want to ask how should I connect L1 to this app. I know there is a LAN port on L1. 
Should I find a wifi router and connect it to L1 by LAN port to LAN port, and then connect smartphone to this router. in this case, what is the IP address? Also should I connect the router online? or it is fine for the router to be offline.
I checked almost every website and there is no answer, I think the only one can answer this is you.
Thank you so much

**Comment by RedyAu** [comment]
Sorry, I didn't get notified of your issue!
Unfortunately, I have no hands-on experience with the L1, but I can try to help.
I'd first try to connect the L1 and a computer running the FeelworldLive app to the same network. The Live app should find the device on the network, and show you the IP address. If you connect your phone with the MultiTally app to this same network, you should be able to connect.
You don't need a working internet connection, just a local network. But watch out: If your WiFi doesn't have internet, your phone will try to use the mobile network instead - tell it to connect to WiFi anyway.

**Comment by RedyAu** [comment]
I will close this for now, but feel free to comment when you're back.
